baseURL: https://rela-v.github.io/
languageCode: en-us
title: rela.v
theme: "PaperMod"

params:
    homeInfoParams:
        Title: rela.v's digital graden
        Content: rela.v's digital garden

    socialIcons: # optional
        - name: "github"
          url: "https://github.com/rela-v"
        - name: "kofi" 
          url: "https://buymeacoffee.com/rela.v"
    ShowReadingTime: true
    author: "rela.v"

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

menu:
    main:
        - identifier: categories
          name: Categories
          url: /categories/
          weight: 10
        - identifier: tags
          name: Tags
          url: /tags/
          weight: 20
        - identifier: search
          name: Search
          url: /search/
          weight: 20
        - identifier: archive
          name: Archive
          url: /archives/
          weight: 20